### ISSUE TITLE
onClick behaviours 

### ISSUE THREAD

**Issue by denissteinhorst** [Tulpep/Notification-Popup-Window#14]
i wish it would be possible (onClick) to:

1) launch another function after that (i have an browser.Reload(); function relating to CefSharp)
2) bring my form1 in front and focus it (its usualy in the background or minimized somewhere)
3) close the notification window on that same click.

is it? - if yes.. please tell me how.

**Comment by YoussefWaelMohamedLotfy** [comment]
There is a Click event when creating an object from PopupNotifier by simply calling popup.Click += OnPopupClick, then in the callback method you can call any method, dispose and hide the popup object.

**Comment by Pulkitsoft** [comment]
Dear @YoussefWaelMohamedLotfy, Can you please provide me with a full sample project or code that invoke click event.

my code

PopupNotifier popup = new PopupNotifier();
popup.Click += OnPopupClick(); // showing error here
popup.TitleText = "License inf";
popup.ContentText = "No of days";
popup.Popup();

private void OnPopupClick(object sender, EventArgs e)
{
  System.Diagnostics.Process.Start("https://www.google.com/")
}

**Comment by jou1187** [comment]
How to .. ??
