### ISSUE TITLE
PopupNotifier object does not dispose

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [Tulpep/Notification-Popup-Window#16]
When I call the dispose method on PopupNotifier Object and observe the debugger, the object seems to be not disposed as the Process Memory does not show any decrease in size.

Here's what i done:
```
        public void ShowPopup()
        {
            popup = new PopupNotifier
            {
                TitleText = "Popup Test",
                ContentText = "Barcode generation success !",
                ShowOptionsButton = true,
                ShowGrip = false,
            };

            popup.Disappear += OnPopupDisappear;
            popup.Close += OnPopupClose;
            popup.Popup();
        }

        private void OnPopupClose(object sender, EventArgs e)
        {
            popup.Dispose();
        }

        private void OnPopupDisappear(object sender, EventArgs e)
        {
            popup.Dispose();
        }
```

**Comment by LiorBanai** [comment]
Hi,
I have forked the repo and fixed  the memory leak and also added support for multi popups.
you can check it here: https://github.com/LiorBanai/Notification-Popup-Window
Nuget: https://www.nuget.org/packages/LiorBanai.NotificationWindow/

**Comment by ricardopolo** [comment]
@LiorBanai would you like to create a PR instead maintaining a new fork?

**Comment by ricardopolo** [comment]
Thank you @LiorBanai for the PR. It's already merged and released a new version in nugget

**Comment by LiorBanai** [comment]
I'll have more PR later this week for other open issues.
