### ISSUE TITLE
Can't set image in vb.net win form application

### ISSUE THREAD

**Issue by zvgronald** [Tulpep/Notification-Popup-Window#18]
popup.Image = Properties.resources.noticon
I get a squiggly line under properties with an error message saying (properties is not declared)

**Comment by LiorBanai** [comment]
I just test it nd it works.
Why aren't you using  My namespace as in:
```vbscript
      Dim notify = New NotificationWindow.PopupNotifier()
      notify.Image = My.Resources.icon
      notify.ContentText = "test"
      notify.Popup()
```

you can see the test project here : https://github.com/LiorBanai/Notification-Popup-Window

test project DemoApp.VB

**Comment by ricardopolo** [comment]
@zvgronald please check the @LiorBanai repo. Looks like there is not an issue in the library. If you still can't fix it please tell us to reopen the issue.

Btw thank so much @LiorBanai !!
