### ISSUE TITLE
Feature: Message notification with sound

### ISSUE THREAD

**Issue by AtlantisDe** [Tulpep/Notification-Popup-Window#19]
### Feature: Message notification with sound
```c# 
hello..can 
Feature: Message notification with sound ?

Thank u Very Much.....
```

```c#
 SoundPlayer simpleSound = new SoundPlayer(@"c:\Windows\Media\chimes.wav");
    simpleSound.Play();
```

**Comment by LiorBanai** [comment]
Hi @AtlantisDe , 
Since it was very easy you can check the implementation at my forked repo.. (and the demo app example).

**Comment by AtlantisDe** [comment]
> Hi @AtlantisDe ,
> Since it was very easy you can check the implementation at my forked repo.. (and the demo app example).

Thank u  very much.....That's ok
