### ISSUE TITLE
A PopupNotifier object cannot be initiated from another thread

### ISSUE THREAD

**Issue by gatlinnewhouse** [Tulpep/Notification-Popup-Window#2]
There doesn't seem to be any code in your library for initiating a PopupNotifier object with the .Popup() method from another thread.

**Comment by gatlinnewhouse** [comment]
The solution can be found at: http://stackoverflow.com/questions/31270559/sending-a-notification-popup-in-winforms-from-another-thread?noredirect=1#comment50535959_31270559

However if I find a way to implement a method to do this in your library I'll submit a pull request.

**Comment by ricardopolo** [comment]
I'll be happy to accept your PR. Thanks! :smile:
