### ISSUE TITLE
Popup not appearing

### ISSUE THREAD

**Issue by lxman** [Tulpep/Notification-Popup-Window#24]
I create a new PopupNotifier, assign a TitleText and a ContentText. I call the Popup method, but nothing is showing on the screen. I have also assigned a handler to the Appear event which does fire, but I see no notification on the screen.

```
using Tulpep.NotificationWindow;

namespace DrakeAccountingScheduler
{
    public static class Notifier
    {
        private static PopupNotifier Notification;

        static Notifier()
        {
            // Use this to dress up our notifier as we wish
        }

        public static void Notify(string title, string message)
        {
            Notification = new PopupNotifier {TitleText = title, ContentText = message};
            Notification.Appear += Notification_Appear;
            Notification.Popup();
        }

        private static void Notification_Appear(object sender, System.EventArgs e)
        {
            
        }
    }
}
```

**Comment by ricardopolo** [comment]
Is this running in in Win32 app? in the user context or do you have some kind of service running?

**Comment by lxman** [comment]
It is a winforms app, .NET framework v4.7.2

Admittedly, the way that I am using this may be a bit non-standard. I am building a separate dll and loading it via reflection and I am attempting to send the notifications from there.

**Comment by ricardopolo** [comment]
Interesting my bet is the DLL is running in another "desktop" (as example System account) and that's why you don't see anything

**Comment by lxman** [comment]
Well, I am using ```Assembly.Load(File.ReadAllBytes("AssemblyLocation"))``` to read it into memory, so I would *think* that it would load it into the same domain as the rest of my application. But you may be right. The only other thing I can think of is the fact that I am doing this over remote desktop. But I've got a separate app where I am using your package and it is working without issue. So I would tend to discount remote desktop as being an issue.

**Comment by ricardopolo** [comment]
What if you create a exe with params that you can use to launch notifications instead a DLL?

So your main programs calls this GUI for showing notifications, and don't bother with the manual DLL loading?

**Comment by lxman** [comment]
I think I have narrowed it down to a thread problem. I believe that the dll that I was loading ended up running on a separate thread. I redesigned my approach so that I could just run the code locally within my program and it works now.
