### ISSUE TITLE
Add Right to Left Support in Title & Content Text!

### ISSUE THREAD

**Issue by vaheeds** [Tulpep/Notification-Popup-Window#7]
It will get even better if you add RTL text support in Title and Content text for users with RTL languages like Persian and Arabic.
Nice work!!!

**Comment by ricardopolo** [comment]
@vaheeds currently I am not being able to do that. If you make a PR that allows that I will be happy to check it, merge it, and release a new version with your changes :)

**Comment by ricardopolo** [comment]
Done!! It was made by @hamid67fathi, so thanks to him. 

If you can test it would be great @vaheeds
